### ISSUE TITLE
Binarized neural network implementation

### ISSUE THREAD

**Issue by nebw** [nebw/argos-zero#7]
* [BMXNet](https://github.com/hpi-xnor/BMXNet)

**Comment by lauraw7** [comment]
Ergebnisse vom 28.02.2018:
- Paper zum BMXNet gelesen (https://arxiv.org/abs/1705.09864)
- Überblick über die Dateien im Github (https://github.com/hpi-xnor/BMXNet) verschafft
- BMXNet heruntergeladen und installiert

**Comment by lauraw7** [comment]
Ergebnisse vom 01.03.2018:

- BMXNet heruntergeladen und Installation auf zweitem Laptop begonnen
- erste Analyse und Erarbeitung des Beispielcodes von BMXNet für den Datensatz MNIST
- Einarbeitung in den Code von Ben (Python-Datei fürs Netzwerktraining) inklusive der verwendeten Netzwerkarchitektur (Frage: Bestimmter Grund, warum gluon verwendet wird?)
- Anmerkung: Für weiteres Vorgehen ist der Trainingsdatensatz hilfreich/notwendig

**Comment by zeehha** [comment]
Abwesend am 28.02.2018.
Zu den Ergebnissen vom 01.03.2018:
- BMXNet läuft schließlich auch auf meinem Laptop, musste mich dazu genauer in Cmake einlesen.
- Paper zum Binarized MXNet gelesen (https://arxiv.org/abs/1705.09864)
- Grundlagen zu Neuronalen Netzen aufgefrischt (Theorie der neuronalen Netze - Rojas)

**Comment by zeehha** [comment]
Ergebnisse vom 02.03.2018:
- Daten runtergeladen, mit squashfuse entpackt (https://github.com/vasi/squashfuse)
- gluon-NN in ein sym-NN "übersetzt" (gluon ist nicht mit BMXNet kompatibel), initialisiert bereits allerdings gibt es beim Training noch Probleme
- git branch (binMXNet) angelegt

**Comment by zeehha** [comment]
Ergebnisse vom 05.03.2018:
- Reduktion der Features und Subsampling der Daten, um Trainingszeit für Tests zu verkürzen
- sym-NN läuft nun auf den originalen Alpha Go Zero Features, sodass dieses im nächsten Schritt in ein binäres sym-NN umgewandelt werden kann

Todos: 
- [x] iteratives Training ermöglichen
- [x] Trainingsprogress während dem Training als Feedback zurückgeben
- [ ] Testen, ob das sym-NN genauso performant ist wie das gluon-NN (zu zeitaufwändig)
- [x] sym-NN in binäres sym-NN transformieren

**Comment by zeehha** [comment]
Ergebnisse vom 06.03.2018:
- iteratives Trainung und Trainingsfeedback umgesetzt, indem wir  model.fit durch .forward, .backward, .update ersetzten, als Metrik haben wir Accuracy verwendet
- Konvertieren des NN in binarized NN ist erfolgreich, Validierungsfunktion geschrieben

Status quo:
nach ersten Tests (mit nur 10 Batches, aber großem Netz) dauert das Klassifizieren mit dem binären NN genauso lange wie mit dem unkonvertierten NN, daher stellt die Anwendung bislang keine Verbesserung dar.

Todos:
- [ ] kleineres NN über mehr Batches austesten
- [x] hpi-examples vergleichen, um Herauszufinden, ob ein Fehler in unserer Umsetzung keine Beschleunigung bringt

**Comment by zeehha** [comment]
Ergebnisse vom 07.03.2018:
- Tests auf den originalen Datensätzen und den bereitgestellten hpi-mnist example bestätigen, dass die Binarisierung für beliebig Netze keinen Speedup liefert (Vermutung: der Speedup resultiert im Wesentlichen aus der Beschleunigung der Matrix-Multiplikation durch Binäroperationen (XNOR und popcount); allerdings hängt die Laufzeit bei Convolutions va. von der `patchToCol` - Funktion ab, see https://github.com/hpi-xnor/BMXNet/issues/6)
- bei NNs welche nur aus Fully-Connected Layern bestehen, erreichen wir im mnist-Setup einen Speedup um Faktor 2 (Beschleunigung durch XNOR Matrix-Multiplikation wirkt sich bei größeren Matritzen stärker aus)
- Speedup Faktoren im BMXNet Paper analysiert, Paper (https://arxiv.org/pdf/1603.05279.pdf) zum ersten Entwurf von binären NN angelesen (diente als Grundlage für BMXNet), Issues von BMXNet zum Speedup gelesen

**Comment by zeehha** [comment]
Nach ausführlichen Tests mit unserem gemischten NN (bestehend aus Convolution und Fully Connected Layers) erreicht die Binarisierung keinen Speedup. Deshalb wird dieses Issue nicht weiter verfolgt.
